[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
